model:
  meta_architecture: "RBSolver"
  rbsolver:
    use_mask: pred
    init_Tc_c2b: [ [ -9.59374011e-01,  2.82136202e-01,  1.67114194e-05,2.35212684e-01 ],
                   [ 9.87813026e-02,  3.35950375e-01, -9.36685324e-01,3.50643694e-01 ],
                   [ -2.64278352e-01, -8.98629963e-01, -3.50172073e-01,1.09972954e+00 ],
                   [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,1.00000000e+00 ] ]
    mesh_paths: [
      "data/franka_description/meshes/visual/link0.ply",
      "data/franka_description/meshes/visual/link1.ply",
      "data/franka_description/meshes/visual/link2.ply",
      "data/franka_description/meshes/visual/link3.ply",
      "data/franka_description/meshes/visual/link4.ply",
      "data/franka_description/meshes/visual/link5.ply",
      "data/franka_description/meshes/visual/link6.ply",
      "data/franka_description/meshes/visual/link7.ply",
      "data/franka_description/meshes/visual/hand.ply",
    ]
    H: 480
    W: 640
datasets:
  train: ("dream_synthetic_panda_test_dr_0",)
  test: "dream_synthetic_panda_test_dr_0"

solver:
  trainer: rbsolver
  num_epochs: 1000 #1000
  max_lr: 0.003
  batch_size: 1000
  save_freq: 1000
  val_freq: 20
  log_interval: 50
  scheduler: "ConstantScheduler"
  save_every: True
  save_mode: iteration
  pop_verts_faces: True
  compress_history_ops: True
  save_optimizer: False
  save_scheduler: False
dataloader:
  pin_memory: True
dataset:
  dream_synthetic_panda_test_dr:
    use_links: [ 0, 1, 2, 3, 4, 5, 6, 7, 9 ]
    load_mask_anno: False
    load_mask_pred: True
test:
  batch_size: 1000
  do_evaluation: True
  evaluators: [ "dream_panda_test" ]
  do_visualization: False
#  visualizer: "rbsolver_hover_mask"
backup_src: False