model:
  meta_architecture: "RBSolverRealmanHead"
  rbsolver:
    H: 480
    W: 640
    use_mask: anno
    init_Tc_c2b: [ [ 0.02004,-0.99975, 0.01032, 0.03559 ],
                   [ 0.98173, 0.02164, 0.18906, 0.05426 ],
                   [ -0.18923, 0.00634, 0.98191,-0.05551 ],
                   [ 0.     , 0.     , 0.     , 1. ] ]

    mesh_paths: [
      #      "data/hillbot_pgi_description_linghao/meshes/Link_left1.STL",
      #                  "data/hillbot_pgi_description_linghao/meshes/Link_left2.STL",
      "data/hillbot_pgi_description_linghao/meshes/Link_right1.STL",
      "data/hillbot_pgi_description_linghao/meshes/Link_right2.STL",
      "data/hillbot_pgi_description_linghao/meshes/Link_right3.STL",
      "data/hillbot_pgi_description_linghao/meshes/Link_right4.STL",
      "data/hillbot_pgi_description_linghao/meshes/Link_right5.STL",
      "data/hillbot_pgi_description_linghao/meshes/Link_right6.STL",
    ]

#    relative_to_link_index: 4
datasets:
  train: ("realman/240618_144800",)
  test: "realman/240618_144800"

solver:
  trainer: "rbsolver"
  num_epochs: 1000
  max_lr: 0.003
  batch_size: 100
  save_freq: 20
  val_freq: 20
  scheduler: "ConstantScheduler"
  save_every: True
  save_mode: iteration
dataloader:
  pin_memory: True
dataset:
  realman:
    relative_to: Link_left6
    camera_id: left
    use_links: [ 7,9,11,13,15,17 ]
    selected_indices: [ 0,1,2,3,4,5,6,7,8,9, 12,13,14,15 ]
test:
  batch_size: 100
  do_evaluation: False
  evaluators: [ "" ]
  do_visualization: True
  visualizer: "rbsolver_hover_mask"

input:
  shuffle: False
