model:
  meta_architecture: "RBSolver"
  rbsolver_iter:
    data_dir: data/sim_for_hec/version2_no_marker_predinit_se_ncam50_nqpos100/000029
  rbsolver:
    use_mask: pred
    init_Tc_c2b: [[ 0.648 , 0.7616,-0.0021, 0.0027],
 [ 0.1365,-0.1189,-0.9835,-0.0019],
 [-0.7493, 0.637 ,-0.181 , 1.1411],
 [ 0.    , 0.    , 0.    , 1.    ]]

    #links: [ 0,1,2,3,4,5,6,7 ]
  space_explorer:
    sample: 50
    sample_limit: True
    n_sample_qposes: 100
    urdf_path: "data/xarm7_with_gripper_reduced_dof.urdf"
    srdf_path: "data/xarm7_with_gripper_reduced_dof.srdf"
    move_group: "link_eef"
    max_dist_constraint:
      enable: True
      max_dist: 0.5
      max_dist_center_compute_n: 20000
    collision_check:
      enable: True
      use_pointcloud: False
      pc_sampled: 40000
      by_eef_pose: False
      ignore_posz_pts: True
      planning_time: 0.1
      dilate: 20
datasets:
  train: ("xarm_hec_sim_version2_no_marker_predinit_se_ncam50_nqpos100/000029",)
  test: "xarm_hec_sim_version2_no_marker_predinit_se_ncam50_nqpos100/000029"

solver:
  trainer: "rbsolver_iter"
  log_interval: 100
  explore_iters: 5
  num_epochs: 1000
  max_lr: 0.003
  batch_size: 100
  save_freq: 20
  val_freq: 20
  scheduler: "ConstantScheduler"
  save_every: True
  save_mode: iteration
dataloader:
  pin_memory: True
dataset:
  xarm_hec_sim:
    load_mask_pred: True
test:
  batch_size: 100
  do_evaluation: False
  evaluators: [ "" ]
  do_visualization: True
  visualizer: "rbsolver_hover_mask"

sim_hec:
  Tc_c2b: [[ 6.48174950e-01, 7.61491453e-01, 0.00000000e+00,-8.52322714e-17],
           [ 1.32231603e-01,-1.12554399e-01,-9.84807753e-01,-3.46023332e-18],
           [-7.49922687e-01, 6.38327717e-01,-1.73648178e-01, 1.13333333e+00],
           [ 0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 1.00000000e+00]]
  step: False
  rt:
    enable: True
  add_desk_cube:
    enable: True
    half_size: [ 0.5, 0.5, 0.5 ]
    pose: [ -0.4, 0, -0.5 ]
