model:
  meta_architecture: "RBSolver"
  rbsolver:
    use_mask: anno
    init_Tc_c2b: [ [ 0.        , 1.        , 0.        ,-0.05 ],
                   [ 0.5       , 0.        ,-0.8660254 , 0.18121778 ],
                   [ -0.8660254 , 0.        ,-0.5       , 1.08612159 ],
                   [ 0.        , 0.        , 0.        , 1. ] ]
    mesh_paths: [
      "data/mobilerobot/mycobot_pi_v2/joint1_fix.stl",
      "data/mobilerobot/mycobot_pi_v2/joint2_fix.stl",
      "data/mobilerobot/mycobot_pi_v2/joint3_fix.stl",
      "data/mobilerobot/mycobot_pi_v2/joint4_fix.stl",
      "data/mobilerobot/mycobot_pi_v2/joint5_fix.stl",
      "data/mobilerobot/mycobot_pi_v2/joint6_fix.stl",
      "data/mobilerobot/mycobot_pi_v2/joint7_fix.stl"
    ]
    H: 1080
    W: 1920
datasets:
  train: ("mobilerobot_20231228",)
  test: "mobilerobot_20231228"

solver:
  trainer: rbsolver
  num_epochs: 1000
  max_lr: 0.003
  batch_size: 1000
  save_freq: 20
  val_freq: 20
  scheduler: "ConstantScheduler"
  save_every: True
  save_mode: iteration
dataloader:
  pin_memory: True
input:
  shuffle: False
dataset:
  mobilerobot:
    load_mask_anno: True
    use_links: [ 0,1,2,3,4,5,6 ]
test:
  batch_size: 1000
  #  do_evaluation: True
  #  evaluators: [ "baxter_ee_pck" ]
  do_visualization: True
  visualizer: "rbsolver_hover_mask"