model:
  meta_architecture: "RBSolver"
  rbsolver:
    use_mask: gt
    init_Tc_c2b: [ [ -7.97280550e-01, -6.03609145e-01,  4.27290797e-06,2.02955887e-01 ],
                   [ -4.16630805e-01,  5.50304115e-01, -7.23591208e-01,3.93981844e-01 ],
                   [ 4.36764002e-01, -5.76906919e-01, -6.90228701e-01,1.03142858e+00 ],
                   [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,1.00000000e+00 ] ]
    mesh_paths: [
      "./ManiSkill2/mani_skill2/assets/descriptions/franka_description/meshes/visual/link0.ply",
      "./ManiSkill2/mani_skill2/assets/descriptions/franka_description/meshes/visual/link1.ply",
      "./ManiSkill2/mani_skill2/assets/descriptions/franka_description/meshes/visual/link2.ply",
      "./ManiSkill2/mani_skill2/assets/descriptions/franka_description/meshes/visual/link3.ply",
      "./ManiSkill2/mani_skill2/assets/descriptions/franka_description/meshes/visual/link4.ply",
      "./ManiSkill2/mani_skill2/assets/descriptions/franka_description/meshes/visual/link5.ply",
      "./ManiSkill2/mani_skill2/assets/descriptions/franka_description/meshes/visual/link6.ply",
      "./ManiSkill2/mani_skill2/assets/descriptions/franka_description/meshes/visual/link7.ply",
      "./ManiSkill2/mani_skill2/assets/descriptions/franka_description/meshes/visual/hand.ply",
    ]
    H: 480
    W: 640
datasets:
  train: ("dream_synthetic_panda_train_dr_0",)
  test: "dream_synthetic_panda_train_dr_0"

solver:
  trainer: rbsolver
  num_epochs: 1000
  max_lr: 0.003
  batch_size: 1000
  save_freq: 20
  val_freq: 20
  scheduler: "ConstantScheduler"
  save_every: True
  save_mode: iteration
dataloader:
  pin_memory: True
dataset:
  dream_synthetic_panda_train_dr:
    use_links: [ 0, 1, 2, 3, 4, 5, 6, 7, 9 ]
    load_mask_anno: False
test:
  batch_size: 1000
  do_evaluation: False
  evaluators: [ "" ]
  do_visualization: True
  visualizer: "rbsolver_hover_mask"
