xarm:
  ip: "192.168.1.209"
  speed: 10
  wait_time: 1
  rotations: [
    [ -20, -20, -20 ],
    [ -15, -15, -20 ],
    [ -15, -10, -15 ],
    [ -10, -10, -10 ],
    [ -10, -5, -5 ],
    [ -5, 0, -5 ],
    [ 0, 0, 0 ],
    [ 5, 5, 0 ],
    [ 5, 10, 5 ],
    [ 10, 10, 10 ],
    [ 15, 10, 15 ],
    [ 20, 15, 15 ],
    [ 20, 20, 20 ],
  ]
  interval: 4
#  axis: x
#  start_from: [ 0,0,0,0,0,0,0 ]