xarm:
  ip: "192.168.1.209"
  speed: 4
  wait_time: 1
  minmax_rotation: [ [ -30, 30 ],[ -30,30 ],[ -30,30 ] ]
  #  minmax_rotation: [ [ -15, 15 ],[ -15,15 ],[ -5,5 ] ]
  interval: 5
#  axis: x
#  start_from: [ 0,0,0,0,0,0,0 ]