model:
  meta_architecture: "RBSolverRealmanHead"
  rbsolver:
    H: 480
    W: 640
    use_mask: anno
    init_Tc_c2b: [ [ -0.95308734,-0.28916537,-0.08953181, 0.45791106 ],
                   [ 0.02435394, 0.22159373,-0.97483788, 0.94668205 ],
                   [ 0.30172371,-0.93127738,-0.20415846, 0.61401935 ],
                   [ 0.        , 0.        , 0.        , 1. ] ]

    mesh_paths: [
      #      "data/hillbot_pgi_description_linghao/meshes/Link_left1.STL",
      #                  "data/hillbot_pgi_description_linghao/meshes/Link_left2.STL",
      "data/hillbot_pgi_description_linghao/meshes/Link_right1.STL",
      "data/hillbot_pgi_description_linghao/meshes/Link_right2.STL",
      "data/hillbot_pgi_description_linghao/meshes/Link_right3.STL",
      "data/hillbot_pgi_description_linghao/meshes/Link_right4.STL",
      "data/hillbot_pgi_description_linghao/meshes/Link_right5.STL",
      "data/hillbot_pgi_description_linghao/meshes/Link_right6.STL",
    ]

#    relative_to_link_index: 4
datasets:
  train: ("realman/240620_130430",)
  test: "realman/240620_130430"

solver:
  trainer: "rbsolver"
  num_epochs: 1000
  max_lr: 0.003
  batch_size: 100
  save_freq: 20
  val_freq: 20
  scheduler: "ConstantScheduler"
  save_every: True
  save_mode: iteration
dataloader:
  pin_memory: True
dataset:
  realman:
    camera_id: left
    use_links: [ 7,9,11,13,15,17 ]
    selected_indices: [ 0,1,2,3,4,5,6,7,8,9, ]
test:
  batch_size: 100
  do_evaluation: False
  evaluators: [ "" ]
  do_visualization: True
  visualizer: "rbsolver_hover_mask"

input:
  shuffle: False
