model:
  meta_architecture: "RBSolver"
  rbsolver:
    eye_in_hand: False
    use_mask: pred
    init_Tc_c2b: [ [ -0.03341358, 0.99933262,-0.01475995, 0.03657149 ],
                   [ 0.43515856, 0.00125188,-0.90035297,-0.0460474 ],
                   [ -0.89973361,-0.03650694,-0.43490997, 1.01310533 ],
                   [ 0.        , 0.        , 0.        , 1. ] ]

    mesh_paths: [ "data/xarm_description/meshes/xarm7/visual/link0.STL",
                  "data/xarm_description/meshes/xarm7/visual/link1.STL",
                  "data/xarm_description/meshes/xarm7/visual/link2.STL",
                  "data/xarm_description/meshes/xarm7/visual/link3.STL",
                  "data/xarm_description/meshes/xarm7/visual/link4.STL",
                  "data/xarm_description/meshes/xarm7/visual/link5.STL",
                  "data/xarm_description/meshes/xarm7/visual/link6.STL",
                  "data/xarm_description/meshes/xarm7/visual/link7.STL",
    ]
datasets:
  train: ("xarm_real_rb_solver_iter/real_xarm/20231105_103622",)
  test: "xarm_real_rb_solver_iter/real_xarm/20231105_103622"
solver:
  trainer: "rbsolver"
  log_interval: 1
  #  explore_iters: 5
  num_epochs: 1000
  max_lr: 0.003
  batch_size: 100
  save_freq: 200
  val_freq: 200
  scheduler: "ConstantScheduler"
  save_every: True
  save_mode: iteration
input:
  shuffle: False
dataloader:
  pin_memory: True
dataset:
  xarm_real:
    load_mask_pred: True
    eye_in_hand: False
    urdf_path: "data/sapien_packages/xarm7/xarm_urdf/xarm7_gripper.urdf"
    use_links: [ 1, 2, 3, 4, 5, 6, 7, 8 ]
    selected_indices: [ 0,1,2,3,4,5,6,7,8 ]
test:
  batch_size: 100
  do_evaluation: False
  evaluators: [ "" ]
  do_visualization: True
  visualizer: "rbsolver_hover_mask"