model:
  meta_architecture: "RBSolverRealmanHead"
  rbsolver:
    H: 480
    W: 640
    use_mask: anno
    init_Tc_c2b: [ [ 0.02639547, 0.87154915,-0.48960439,-0.43165404 ],
                   [ -0.9981152 ,-0.0041628 ,-0.06122538, 0.06355373 ],
                   [ -0.05539923, 0.49029237, 0.86980038, 0.12371277 ],
                   [ 0.        , 0.        , 0.        , 1. ] ]

    mesh_paths: [
      #      "data/hillbot_pgi_description_linghao/meshes/Link_left1.STL",
      #                  "data/hillbot_pgi_description_linghao/meshes/Link_left2.STL",
      "data/hillbot_pgi_description_linghao/meshes/Link_right3.STL",
      "data/hillbot_pgi_description_linghao/meshes/Link_right4.STL",
      "data/hillbot_pgi_description_linghao/meshes/Link_right5.STL",
      "data/hillbot_pgi_description_linghao/meshes/Link_right6.STL",
    ]

#    relative_to_link_index: 4
datasets:
  train: ("realman/240617-131349",)
  test: "realman/240617-131349"

solver:
  trainer: "rbsolver"
  num_epochs: 1000
  max_lr: 0.003
  batch_size: 100
  save_freq: 20
  val_freq: 20
  scheduler: "ConstantScheduler"
  save_every: True
  save_mode: iteration
dataloader:
  pin_memory: True
dataset:
  realman:
    relative_to: Link_rbase
    camera_id: left
    use_links: [ 11,13,15,17 ]
    selected_indices: [ 0,1,2,3,4,5,6,7,8,9 ]
test:
  batch_size: 100
  do_evaluation: False
  evaluators: [ "" ]
  do_visualization: True
  visualizer: "rbsolver_hover_mask"

input:
  shuffle: False
