model:
  meta_architecture: "RBSolver"
  rbsolver_iter:
    data_dir: data/rb_solver_iter/real_xarm/example4

    use_realarm:
      enable: True
      ip: "192.168.1.209"
      speed: 0.1
      wait_time: 1
      speed_control: True
      safety_factor: 6
      timestep: 0.05
    #      record_video:
    #        enable: True
    pointrend_cfg_file: "configs/InstanceSegmentation/pointrend_rcnn_R_50_FPN_3x_xarm_finetune_v1v2_aug.yaml"
    pointrend_model_weight: "models/pointrend_rcnn_R_50_FPN_3x_xarm_finetune_v1v2_aug/model_final.pth"
  rbsolver:
    use_mask: pred
    init_Tc_c2b: [ [ 0.95921475,  0.28230679,  0.01448959, -0.24205755 ],
                   [ 0.11272016, -0.33498466, -0.93545675, 0.10301555 ],
                   [ -0.25923201,  0.89893723, -0.35314393,  0.73993033 ],
                   [ 0.        ,  0.        ,  0.        ,  1. ] ]

    mesh_paths: [ "data/xarm_description/meshes/xarm7/visual/link1.STL",
                  "data/xarm_description/meshes/xarm7/visual/link2.STL",
                  "data/xarm_description/meshes/xarm7/visual/link3.STL",
                  "data/xarm_description/meshes/xarm7/visual/link4.STL",
                  "data/xarm_description/meshes/xarm7/visual/link5.STL",
                  "data/xarm_description/meshes/xarm7/visual/link6.STL",
                  "data/xarm_description/meshes/xarm7/visual/link7.STL", ]
  space_explorer:
    parallel_rendering: True
    sample: 10 #50
    sample_limit: True
    n_sample_qposes: 500 #2000
    urdf_path: "data/xarm7_with_gripper_reduced_dof.urdf"
    srdf_path: "data/xarm7_with_gripper_reduced_dof.srdf"
    move_group: "link_eef"
    max_dist_constraint:
      enable: True
      max_dist: 0.5
      max_dist_center_compute_n: 20000
    collision_check:
      enable: True
      use_pointcloud: False # use hard-coded model to perform collision check
      pc_sampled: 40000
      ignore_posz_pts: True
      dilate: 20
      by_eef_pose: False
#      timestep: 0.02
datasets:
  train: ("xarm_real_rb_solver_iter/real_xarm/example4",)
  test: "xarm_real_rb_solver_iter/real_xarm/example4"

solver:
  trainer: "rbsolver_iter"
  log_interval: 100
  explore_iters: 5
  num_epochs: 800 #1000
  max_lr: 0.003
  batch_size: 100
  save_freq: 20
  val_freq: 20
  scheduler: "ConstantScheduler"
  save_every: True
  save_mode: iteration
input:
  shuffle: False
dataloader:
  pin_memory: True
dataset:
  xarm_real:
    load_mask_pred: True
test:
  batch_size: 100
  do_evaluation: False
  evaluators: [ "" ]
  do_visualization: False
  visualizer: "rbsolver_hover_mask"

sim_hec:
  Tc_c2b: [ [ 9.738e-01,  2.276e-01,  0.000e+00,  2.704e-17 ],
            [ 7.784e-02, -3.330e-01, -9.397e-01,  3.372e-17 ],
            [ -2.139e-01,  9.150e-01, -3.420e-01,  8.000e-01 ],
            [ 0.000e+00,  0.000e+00,  0.000e+00,  1.000e+00 ] ]
  step: False
  rt:
    enable: True
  add_desk_cube:
    enable: True
    half_size: [ 0.5, 0.5, 0.5 ]
    pose: [ -0.4, 0, -0.5 ]
