annotate_video:
  data_dir: data/realsense/5cmcube_trainset2
  #  n: 10
  whl: [ 0.05,0.05,0.05 ]
  pts_3d: [ [ 0.025 , 0.025 , 0.025 ],
            [ 0.025 ,-0.025 , 0.025 ],
            [ -0.025,  0.025 , 0.025 ],
            [ -0.025, -0.025 , 0.025 ],
            [ 0.025 , 0.025, -0.025 ],
    #            [ 0.025 -0.025 -0.025 ]
            [ -0.025 , 0.025, -0.025 ],
            [ -0.025, -0.025, -0.025 ] ]
  use_aruco: True
  aruco:
    rows: 4
    cols: 7
    marker_size: 0.03
    marker_sep: 0.005
    dictionary: "DICT_ARUCO_ORIGINAL"