xarm:
  ip: "192.168.1.209"
  speed: 4
  wait_time: 1
  angles:
    #    - [ 10,0,0,0,0,0 ]
    #    - [ 0,-10,0,0,0,0 ]
    #    - [ 0,0,10,0,0,0 ]
    #    - [ 0,0,0,10,0,0 ]
    #    - [ 0,0,0,0,10,0 ]
    - [ 0,0,0,0,0,10 ]
  delta_rotation: 35
  axis: x