model:
  meta_architecture: "RBSolver"
  rbsolver_iter:
    data_dir: data/sim_for_hec/version2_no_marker_se_rand/000089
  rbsolver:
    use_mask: pred
    init_Tc_c2b: [[ 6.48174950e-01, 7.61491453e-01, 0.00000000e+00, 1.17842757e-16],
 [ 3.80745727e-01,-3.24087475e-01,-8.66025404e-01,-9.53510301e-17],
 [-6.59470943e-01, 5.61335973e-01,-5.00000000e-01, 1.80000000e+00],
 [ 0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 1.00000000e+00]]

    #links: [ 0,1,2,3,4,5,6,7 ]
  space_explorer:
    variance_based_sampling: False
    sample: 50
    sample_limit: True
    n_sample_qposes: 2000
    urdf_path: "data/xarm7_with_gripper_reduced_dof.urdf"
    srdf_path: "data/xarm7_with_gripper_reduced_dof.srdf"
    move_group: "link_eef"
    max_dist_constraint:
      enable: True
      max_dist: 0.5
      max_dist_center_compute_n: 20000
    collision_check:
      enable: True
      pc_sampled: 40000
      ignore_posz_pts: True
      dilate: 20
datasets:
  train: ("xarm_hec_sim_version2_no_marker_se_rand/000089",)
  test: "xarm_hec_sim_version2_no_marker_se_rand/000089"

solver:
  trainer: "rbsolver_iter"
  log_interval: 100
  explore_iters: 5
  num_epochs: 1000
  max_lr: 0.003
  batch_size: 100
  save_freq: 20
  val_freq: 20
  scheduler: "ConstantScheduler"
  save_every: True
  save_mode: iteration
dataloader:
  pin_memory: True
dataset:
  xarm_hec_sim:
    load_mask_pred: True
test:
  batch_size: 100
  do_evaluation: False
  evaluators: [ "" ]
  do_visualization: True
  visualizer: "rbsolver_hover_mask"

sim_hec:
  Tc_c2b: [[ 6.48174950e-01, 7.61491453e-01, 0.00000000e+00, 1.17842757e-16],
           [ 3.80745727e-01,-3.24087475e-01,-8.66025404e-01,-9.53510301e-17],
           [-6.59470943e-01, 5.61335973e-01,-5.00000000e-01, 1.80000000e+00],
           [ 0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 1.00000000e+00]]
  step: False
  rt:
    enable: True
  add_desk_cube:
    enable: True
    half_size: [ 0.5, 0.5, 0.5 ]
    pose: [ -0.4, 0, -0.5 ]
