link_name_mesh_path_mapping = {
    'base_link': "data/hillbot_pgi_description_linghao/meshes/base_link.STL",
    'Link_rail': "data/hillbot_pgi_description_linghao/meshes/Link_rail.STL",
    'Link_lbase': "data/hillbot_pgi_description_linghao/meshes/Link_lbase.STL",
    'Link_left1': "data/hillbot_pgi_description_linghao/meshes/Link_left1.STL",
    'Link_left2': "data/hillbot_pgi_description_linghao/meshes/Link_left2.STL",
    'Link_left3': "data/hillbot_pgi_description_linghao/meshes/Link_left3.STL",
    'Link_left4': "data/hillbot_pgi_description_linghao/meshes/Link_left4.STL",
    'Link_left5': "data/hillbot_pgi_description_linghao/meshes/Link_left5.STL",
    'Link_left6': "data/hillbot_pgi_description_linghao/meshes/Link_left6.STL",
    'gripper_base_link_left': "data/hillbot_pgi_description_linghao/meshes/gripper_base_link_left.STL",
    'finger_link_left1': "data/hillbot_pgi_description_linghao/meshes/finger_link_left1.STL",
    'finger_link_left2': "data/hillbot_pgi_description_linghao/meshes/finger_link_left2.STL",
    'Link_rbase': "data/hillbot_pgi_description_linghao/meshes/Link_rbase.STL",
    'Link_right1': "data/hillbot_pgi_description_linghao/meshes/Link_right1.STL",
    'Link_right2': "data/hillbot_pgi_description_linghao/meshes/Link_right2.STL",
    'Link_right3': "data/hillbot_pgi_description_linghao/meshes/Link_right3.STL",
    'Link_right4': "data/hillbot_pgi_description_linghao/meshes/Link_right4.STL",
    'Link_right5': "data/hillbot_pgi_description_linghao/meshes/Link_right5.STL",
    'Link_right6': "data/hillbot_pgi_description_linghao/meshes/Link_right6.STL",
    'gripper_base_link_right': "data/hillbot_pgi_description_linghao/meshes/gripper_base_link_right.STL",
    'finger_link_right1': "data/hillbot_pgi_description_linghao/meshes/finger_link_right1.STL",
    'finger_link_right2': "data/hillbot_pgi_description_linghao/meshes/finger_link_right2.STL",
    'Link_head1': "data/hillbot_pgi_description_linghao/meshes/Link_head1.STL",
    'Link_head2': "data/hillbot_pgi_description_linghao/meshes/Link_head2.STL",
}
