model:
  meta_architecture: "RBSolver"
  rbsolver:
    use_mask: pred
    init_Tc_c2b: [ [ 0.99567632, 0.05677649, 0.07351936,-0.30625624 ],
                   [ 0.0848831 ,-0.23464434,-0.96836816, 0.16773671 ],
                   [ -0.03772964, 0.9704218 ,-0.23844918, 0.96733699 ],
                   [ 0.        , 0.        , 0.        , 1. ] ]

#  space_explorer:
#    variance_based_sampling: False
#    sample_limit: True
#    n_sample_qposes: 2000
#    urdf_path: "data/xarm7_with_gripper_reduced_dof.urdf"
#    srdf_path: "data/xarm7_with_gripper_reduced_dof.srdf"
#    move_group: "link_eef"
#    max_dist_constraint:
#      enable: True
#      max_dist: 0.5
#      max_dist_center_compute_n: 20000
#    collision_check:
#      enable: True
#      pc_sampled: 40000
datasets:
  train: ("xarm_hec_sim_autoinit/real",)
  test: "xarm_hec_sim_autoinit/real"

solver:
  trainer: rbsolver
  num_epochs: 1000
  max_lr: 0.003
  batch_size: 100
  save_freq: 20
  val_freq: 20
  scheduler: "ConstantScheduler"
  save_every: True
  save_mode: iteration
dataloader:
  pin_memory: True
input:
  shuffle: False
dataset:
  xarm_hec_sim:
    load_mask_pred: True
    load_mask_gt: False
test:
  batch_size: 100
  do_evaluation: False
  evaluators: [ "" ]
  do_visualization: True
  visualizer: "rbsolver_hover_mask"


#  space_explore:
#    start: 300
#    sample: 50 # camera poses sampled from start to end (steps[-1])
#    #    sample: 10 # camera poses sampled from start to end (steps[-1])
#    qpos_sample_method: random
#    n_sample_qposes: 1500
##    n_sample_qposes: 500
