maskrcnn:
  data_dir: "data/sim/render_for_mrcnn_ring_rt_merged"
  model_cfg_file: "COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x.yaml"
  base_lr: 0.0025
  max_iter: 16000
  batch_size: 12
  batch_size_per_image: 512
  num_workers: 4
  score_thresh_test: 0.7
  checkpoint_period: 5000