model:
  meta_architecture: "RBSolver"
  rbsolver_iter:
    data_dir: data/sim_for_hec/version2_no_marker_predinit_se_ncam50_nqpos1500/000013
  rbsolver:
    use_mask: pred
    init_Tc_c2b: [[ 7.679e-01, 6.406e-01,-2.000e-04, 3.100e-03],
 [ 2.705e-01,-3.245e-01,-9.064e-01,-1.000e-03],
 [-5.807e-01, 6.959e-01,-4.224e-01, 7.967e-01],
 [ 0.000e+00, 0.000e+00, 0.000e+00, 1.000e+00]]

    #links: [ 0,1,2,3,4,5,6,7 ]
  space_explorer:
    sample: 50
    sample_limit: True
    n_sample_qposes: 1500
    urdf_path: "data/xarm7_with_gripper_reduced_dof.urdf"
    srdf_path: "data/xarm7_with_gripper_reduced_dof.srdf"
    move_group: "link_eef"
    max_dist_constraint:
      enable: True
      max_dist: 0.5
      max_dist_center_compute_n: 20000
    collision_check:
      enable: True
      use_pointcloud: False
      pc_sampled: 40000
      by_eef_pose: False
      ignore_posz_pts: True
      planning_time: 0.1
      dilate: 20
datasets:
  train: ("xarm_hec_sim_version2_no_marker_predinit_se_ncam50_nqpos1500/000013",)
  test: "xarm_hec_sim_version2_no_marker_predinit_se_ncam50_nqpos1500/000013"

solver:
  trainer: "rbsolver_iter"
  log_interval: 100
  explore_iters: 5
  num_epochs: 1000
  max_lr: 0.003
  batch_size: 100
  save_freq: 20
  val_freq: 20
  scheduler: "ConstantScheduler"
  save_every: True
  save_mode: iteration
dataloader:
  pin_memory: True
dataset:
  xarm_hec_sim:
    load_mask_pred: True
test:
  batch_size: 100
  do_evaluation: False
  evaluators: [ "" ]
  do_visualization: True
  visualizer: "rbsolver_hover_mask"

sim_hec:
  Tc_c2b: [[ 7.93893273e-01, 6.08057128e-01, 0.00000000e+00, 1.98888439e-17],
           [ 3.04028564e-01,-3.96946637e-01,-8.66025404e-01, 5.63082555e-17],
           [-5.26592920e-01, 6.87531742e-01,-5.00000000e-01, 8.00000000e-01],
           [ 0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 1.00000000e+00]]
  step: False
  rt:
    enable: True
  add_desk_cube:
    enable: True
    half_size: [ 0.5, 0.5, 0.5 ]
    pose: [ -0.4, 0, -0.5 ]
