model:
  meta_architecture: "RBSolver"
  rbsolver:
    use_mask: pred
    init_Tc_c2b: [ [ 7.66044443e-01, 6.42787610e-01, 0.00000000e+00,-8.83981060e-19 ],
                   [ 2.91050283e-01,-3.46860221e-01,-8.91615231e-01, 5.45607496e-17 ],
                   [ -5.73119223e-01, 6.83016893e-01,-4.52793860e-01, 1.00000000e+00 ],
                   [ 0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 1.00000000e+00 ] ]
datasets:
  train: ("xarm_hec_sim_autoinit/000013",)
  test: "xarm_hec_sim_autoinit/000013"

solver:
  trainer: rbsolver
  num_epochs: 300
  max_lr: 0.003
  batch_size: 100
  save_freq: 20
  val_freq: 20
  scheduler: "ConstantScheduler"
  save_every: True
  save_mode: iteration
dataloader:
  pin_memory: True
input:
  shuffle: False
dataset:
  xarm_hec_sim:
    load_mask_pred: True
#    load_mask_gt: False
test:
  batch_size: 100
  do_evaluation: False
  evaluators: [ "" ]
  do_visualization: True
  visualizer: "rbsolver_hover_mask"


#  space_explore:
#    start: 300
#    sample: 50 # camera poses sampled from start to end (steps[-1])
#    #    sample: 10 # camera poses sampled from start to end (steps[-1])
#    qpos_sample_method: random
#    n_sample_qposes: 1500
##    n_sample_qposes: 500
