model:
  meta_architecture: "RBSolver"
  rbsolver:
    use_mask: pred
    init_Tc_c2b: [ [ 7.66044443e-01, 6.42787610e-01, 0.00000000e+00, 3.47279546e-17 ],
                   [ 6.03198253e-02,-7.18863685e-02,-9.95587198e-01,-1.00815949e-19 ],
                   [ -6.39951115e-01, 7.62664041e-01,-9.38409894e-02, 1.00000000e+00 ],
                   [ 0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 1.00000000e+00 ] ]
datasets:
  train: ("xarm_hec_sim_autoinit/000028",)
  test: "xarm_hec_sim_autoinit/000028"

solver:
  trainer: rbsolver
  num_epochs: 300
  max_lr: 0.003
  batch_size: 100
  save_freq: 20
  val_freq: 20
  scheduler: "ConstantScheduler"
  save_every: True
  save_mode: iteration
dataloader:
  pin_memory: True
input:
  shuffle: False
dataset:
  xarm_hec_sim:
    load_mask_pred: True
#    load_mask_gt: False
test:
  batch_size: 100
  do_evaluation: False
  evaluators: [ "" ]
  do_visualization: True
  visualizer: "rbsolver_hover_mask"


#  space_explore:
#    start: 300
#    sample: 50 # camera poses sampled from start to end (steps[-1])
#    #    sample: 10 # camera poses sampled from start to end (steps[-1])
#    qpos_sample_method: random
#    n_sample_qposes: 1500
##    n_sample_qposes: 500
