model:
  meta_architecture: "RBSolver"
  rbsolver:
    use_mask: mask_gsam
    #    optim_trans_only: True
    #    init_Tc_c2b: [ [ 0.80685358, 0.58882665,-0.04764955,-0.80215376 ],
    #                   [ -0.11633088, 0.07928819,-0.99004066, 0.19772471 ],
    #                   [ -0.57918428, 0.80436096, 0.13247269, 1.29090092 ],
    #                   [ 0.        , 0.        , 0.        , 1. ] ]
    init_Tc_c2b: [ [ 5.87785252e-01, 8.09016994e-01, 9.28930585e-18,-9.92293749e-01 ],
                   [ 1.63597453e-01,-1.18860507e-01,-9.79340622e-01, 3.85503112e-01 ],
                   [ -7.92303206e-01, 5.75641974e-01,-2.02217572e-01, 2.10559101e+00 ],
                   [ 0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 1.00000000e+00 ] ]

    mesh_paths: [
      "data/baxter_common/baxter_description/meshes/upper_shoulder/S0.STL",
      "data/baxter_common/baxter_description/meshes/lower_shoulder/S1.STL",
      "data/baxter_common/baxter_description/meshes/upper_elbow/E0.STL",
      "data/baxter_common/baxter_description/meshes/lower_elbow/E1.STL",
      "data/baxter_common/baxter_description/meshes/upper_forearm/W0.STL",
      "data/baxter_common/baxter_description/meshes/lower_forearm/W1.STL",
    ]
    render_scale: 4.0
    H: 1536
    W: 2048
datasets:
  train: ("baxter_real_all",)
  test: "baxter_real_all"

solver:
  trainer: rbsolver
  num_epochs: 1000
  max_lr: 0.003
  batch_size: 100
  save_freq: 20
  val_freq: 20
  scheduler: "ConstantScheduler"
  save_every: True
  save_mode: iteration
dataloader:
  pin_memory: True
input:
  shuffle: False
dataset:
  baxter_real:
    load_mask_gsam: True
    #    selected_indices: [ 0,1,3,4,5,6,7,9,10,11,14,16,17,18,19 ]
    selected_indices: [ 0, 19 ,14, 10,  5,  3, 16, 17,  6, 18 ]
#    use_links: [ 33, 34, 35, 36, 38 ]
test:
  batch_size: 100
  do_evaluation: False
  evaluators: [ "" ]
  do_visualization: True
  visualizer: "rbsolver_hover_mask"
