model:
  meta_architecture: "RBSolverRealmanHead"
  rbsolver:
    H: 480
    W: 640
    use_mask: anno
    init_Tc_c2b: [ [ 0.00000001,-1.        ,-0.        ,-0.00000002 ],
                   [ -0.76604444,-0.00000001,-0.6427876 , 1.1244153 ],
                   [ 0.6427876 , 0.00000001,-0.76604444, 1.3175849 ],
                   [ 0.        , 0.        , 0.        , 1. ] ]

    mesh_paths: [ "data/hillbot_pgi_description_linghao/meshes/Link_left1.STL",
                  "data/hillbot_pgi_description_linghao/meshes/Link_right1.STL",
                  "data/hillbot_pgi_description_linghao/meshes/Link_left2.STL",
                  "data/hillbot_pgi_description_linghao/meshes/Link_right2.STL",
                  "data/hillbot_pgi_description_linghao/meshes/Link_left3.STL",
                  "data/hillbot_pgi_description_linghao/meshes/Link_right3.STL",
                  "data/hillbot_pgi_description_linghao/meshes/Link_left4.STL",
                  "data/hillbot_pgi_description_linghao/meshes/Link_right4.STL",
                  "data/hillbot_pgi_description_linghao/meshes/Link_left5.STL",
                  "data/hillbot_pgi_description_linghao/meshes/Link_right5.STL",
                  "data/hillbot_pgi_description_linghao/meshes/Link_left6.STL",
                  "data/hillbot_pgi_description_linghao/meshes/Link_right6.STL",
    ]
datasets:
  train: ("realman/240612-095351",)
  test: "realman/240612-095351"

solver:
  trainer: "rbsolver"
  num_epochs: 1000
  max_lr: 0.003
  batch_size: 100
  save_freq: 20
  val_freq: 20
  scheduler: "ConstantScheduler"
  save_every: True
  save_mode: iteration
dataloader:
  pin_memory: True
dataset:
  realman:
    use_links: [ 6, 7, 8, 9, 10, 11, 12, 13, 14, 15,16,17 ]
    selected_indices: [ 0,1,2,3,4,5,6,7,8,9 ]
test:
  batch_size: 100
  do_evaluation: False
  evaluators: [ "" ]
  do_visualization: True
  visualizer: "rbsolver_hover_mask"

input:
  shuffle: False
