model:
  meta_architecture: "RBSolver"
  rbsolver_iter:
    data_dir: data/sim_for_hec/version2_no_marker_predinit_se_autosam/000028
    segmentor: autosam
    init_method: meshloc # manual, pvnet, or meshloc
    meshloc_database_dir: "data/sim_for_hec/version2_no_marker_predinit_se_autosam/meshloc_database"
  rbsolver:
    use_mask: pred
    init_Tc_c2b: [ ]
  space_explorer:
    sample: 20
    sample_limit: True
    n_sample_qposes: 1000
    urdf_path: "data/xarm7_with_gripper_reduced_dof.urdf"
    srdf_path: "data/xarm7_with_gripper_reduced_dof.srdf"
    move_group: "link_eef"
    max_dist_constraint:
      enable: True
      max_dist_center: 0.24
      max_dist: 0.5
      max_dist_center_compute_n: 20000
    collision_check:
      enable: True
      use_pointcloud: False
      by_eef_pose: False
      planning_time: 0.1
      pc_sampled: 40000
      ignore_posz_pts: True
      dilate: 20
datasets:
  train: ("xarm_hec_sim_version2_no_marker_predinit_se_autosam/000028",)
  test: "xarm_hec_sim_version2_no_marker_predinit_se_autosam/000028"

solver:
  trainer: "rbsolver_iter"
  log_interval: 100
  explore_iters: 5
  num_epochs: 1000
  max_lr: 0.003
  batch_size: 100
  save_freq: 20
  val_freq: 20
  scheduler: "ConstantScheduler"
  save_every: True
  save_mode: iteration
dataloader:
  pin_memory: True
dataset:
  xarm_hec_sim:
    load_mask_pred: True
test:
  batch_size: 100
  do_evaluation: False
  evaluators: [ "" ]
  do_visualization: True
  visualizer: "rbsolver_hover_mask"

sim_hec:
  Tc_c2b: [ [ 7.93893273e-01, 6.08057128e-01, 0.00000000e+00,-5.15622043e-18 ],
            [ 1.05588012e-01,-1.37858120e-01,-9.84807753e-01,-3.46023332e-18 ],
            [ -5.98819374e-01, 7.81832250e-01,-1.73648178e-01, 1.13333333e+00 ],
            [ 0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 1.00000000e+00 ] ]
  step: False
  rt:
    enable: True
  add_desk_cube:
    enable: True
    half_size: [ 0.5, 0.5, 0.5 ]
    pose: [ -0.4, 0, -0.5 ]
