model:
  meta_architecture: "RBSolver"
  rbsolver_iter:
    data_dir: data/baxter_real/pred_mask_init_prov_se
    data_pool: [
      "/home/linghao/Datasets/baxter_real/baxter-real-dataset/processed/000000",
      "/home/linghao/Datasets/baxter_real/baxter-real-dataset/processed/000005",
      "/home/linghao/Datasets/baxter_real/baxter-real-dataset/processed/000010",
      "/home/linghao/Datasets/baxter_real/baxter-real-dataset/processed/000015",
      "/home/linghao/Datasets/baxter_real/baxter-real-dataset/processed/000020",
      "/home/linghao/Datasets/baxter_real/baxter-real-dataset/processed/000025",
      "/home/linghao/Datasets/baxter_real/baxter-real-dataset/processed/000030",
      "/home/linghao/Datasets/baxter_real/baxter-real-dataset/processed/000035",
      "/home/linghao/Datasets/baxter_real/baxter-real-dataset/processed/000040",
      "/home/linghao/Datasets/baxter_real/baxter-real-dataset/processed/000045",
      "/home/linghao/Datasets/baxter_real/baxter-real-dataset/processed/000050",
      "/home/linghao/Datasets/baxter_real/baxter-real-dataset/processed/000055",
      "/home/linghao/Datasets/baxter_real/baxter-real-dataset/processed/000060",
      "/home/linghao/Datasets/baxter_real/baxter-real-dataset/processed/000065",
      "/home/linghao/Datasets/baxter_real/baxter-real-dataset/processed/000070",
      "/home/linghao/Datasets/baxter_real/baxter-real-dataset/processed/000075",
      "/home/linghao/Datasets/baxter_real/baxter-real-dataset/processed/000080",
      "/home/linghao/Datasets/baxter_real/baxter-real-dataset/processed/000085",
      "/home/linghao/Datasets/baxter_real/baxter-real-dataset/processed/000090",
      "/home/linghao/Datasets/baxter_real/baxter-real-dataset/processed/000095",
    ]
    start_index: 7
  rbsolver:
    use_mask: pred
    init_Tc_c2b: [ [ 0.3575719 ,  0.93387324, -0.00480661, -0.8592802 ],
                   [ -0.11172229,  0.03766659, -0.9930254 ,  0.30743563 ],
                   [ -0.9271785 ,  0.3556154 ,  0.11780312,  1.2090743 ],
                   [ 0.        ,  0.        ,  0.        ,  1. ] ]
    mesh_paths: [
      "./baxter_common/baxter_description/meshes/upper_shoulder/S0.STL",
      "./baxter_common/baxter_description/meshes/lower_shoulder/S1.STL",
      "./baxter_common/baxter_description/meshes/upper_elbow/E0.STL",
      "./baxter_common/baxter_description/meshes/lower_elbow/E1.STL",
      "./baxter_common/baxter_description/meshes/upper_forearm/W0.STL",
      "./baxter_common/baxter_description/meshes/lower_forearm/W1.STL",
    ]
    H: 1536
    W: 2048
  space_explorer:
    qpos_choices: "/home/linghao/Datasets/baxter_real/baxter-real-dataset/cleaned/joints.txt"
    qpos_choices_pad_left: 8
    sample: 50
    start: 200
    #    sample_limit: True # not used
    #    n_sample_qposes: 2000 # not used

    urdf_path: "./baxter_common/baxter.urdf"
    srdf_path: "" # not used
    move_group: "" # not used

    self_collision_check:
      enable: False
    max_dist_constraint:
      enable: False
    collision_check:
      enable: False
datasets:
  train: ("baxter_real_se_pred_mask_init_prov_se",)
  test: "baxter_real_se_pred_mask_init_prov_se"

solver:
  trainer: "rbsolver_iter"
  log_interval: 100
  explore_iters: 3
  num_epochs: 1000
  max_lr: 0.003
  batch_size: 100
  save_freq: 20
  val_freq: 20
  scheduler: "ConstantScheduler"
  save_every: True
  save_mode: iteration
dataloader:
  pin_memory: True
dataset:
  baxter_real:
    load_mask_pred: True
test:
  batch_size: 100
  do_evaluation: True
  evaluators: [ "baxter_iter_ee_pck" ]
  do_visualization: False
  visualizer: ""

#sim_hec:
#  Tc_c2b: [ [ 0.99987525, 0.00185839, 0.01568501, -0.28588107 ],
#            [ 0.0157616, -0.18167329, -0.98323268, 0.05843821 ],
#            [ 0.00102232, 0.98335725, -0.18167984, 0.95864612 ],
#            [ 0., 0., 0., 1. ] ]
#  step: False
#  rt:
#    enable: True
#  add_desk_cube:
#    enable: True
#    half_size: [ 0.5, 0.5, 0.5 ]
#    pose: [ -0.4, 0, -0.5 ]