model:
  meta_architecture: "RBSolver"
  rbsolver_iter:
    data_dir: data/sim_for_hec/version2_no_marker_predinit_se_ncam20_nqpos2000/000008
  rbsolver:
    use_mask: pred
    init_Tc_c2b: [[ 0.8115, 0.5842,-0.0139, 0.0053],
 [ 0.2007,-0.301 ,-0.9323,-0.0168],
 [-0.5488, 0.7537,-0.3615, 0.8298],
 [ 0.    , 0.    , 0.    , 1.    ]]

    #links: [ 0,1,2,3,4,5,6,7 ]
  space_explorer:
    sample: 20
    sample_limit: True
    n_sample_qposes: 2000
    urdf_path: "data/xarm7_with_gripper_reduced_dof.urdf"
    srdf_path: "data/xarm7_with_gripper_reduced_dof.srdf"
    move_group: "link_eef"
    max_dist_constraint:
      enable: True
      max_dist: 0.5
      max_dist_center_compute_n: 20000
    collision_check:
      enable: True
      use_pointcloud: False
      pc_sampled: 40000
      by_eef_pose: False
      ignore_posz_pts: True
      planning_time: 0.1
      dilate: 20
datasets:
  train: ("xarm_hec_sim_version2_no_marker_predinit_se_ncam20_nqpos2000/000008",)
  test: "xarm_hec_sim_version2_no_marker_predinit_se_ncam20_nqpos2000/000008"

solver:
  trainer: "rbsolver_iter"
  log_interval: 100
  explore_iters: 5
  num_epochs: 1000
  max_lr: 0.003
  batch_size: 100
  save_freq: 20
  val_freq: 20
  scheduler: "ConstantScheduler"
  save_every: True
  save_mode: iteration
dataloader:
  pin_memory: True
dataset:
  xarm_hec_sim:
    load_mask_pred: True
test:
  batch_size: 100
  do_evaluation: False
  evaluators: [ "" ]
  do_visualization: True
  visualizer: "rbsolver_hover_mask"

sim_hec:
  Tc_c2b: [[ 7.93893273e-01, 6.08057128e-01, 0.00000000e+00,-1.30170079e-17],
           [ 2.07967786e-01,-2.71527491e-01,-9.39692621e-01, 8.92275814e-17],
           [-5.71386796e-01, 7.46015650e-01,-3.42020143e-01, 8.00000000e-01],
           [ 0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 1.00000000e+00]]
  step: False
  rt:
    enable: True
  add_desk_cube:
    enable: True
    half_size: [ 0.5, 0.5, 0.5 ]
    pose: [ -0.4, 0, -0.5 ]
