model:
  meta_architecture: "RBSolver"
  rbsolver_iter:
    data_dir: data/sim_for_hec/version2_no_marker_se_rt_autosam_alllink/000007
    segmentor: autosam
    init_method: meshloc # manual, pvnet, or meshloc
    meshloc_database_dir: "data/sim_for_hec/version2_no_marker_predinit_se_autosam/meshloc_database"
    autosam_links: [ 8 ]
  rbsolver:
    use_mask: pred
    init_Tc_c2b: [ ]
  space_explorer:
    sample: 20
    sample_limit: True
    n_sample_qposes: 1000
    urdf_path: "data/xarm7_with_gripper_reduced_dof.urdf"
    srdf_path: "data/xarm7_with_gripper_reduced_dof.srdf"
    move_group: "link_eef"
    max_dist_constraint:
      enable: True
      max_dist_center: 0.24
      max_dist: 0.5
      max_dist_center_compute_n: 20000
    collision_check:
      enable: True
      use_pointcloud: False
      by_eef_pose: False
      planning_time: 0.1
      pc_sampled: 40000
      ignore_posz_pts: True
      dilate: 20
datasets:
  train: ("xarm_hec_sim_version2_no_marker_se_rt_autosam_alllink/000007",)
  test: "xarm_hec_sim_version2_no_marker_se_rt_autosam_alllink/000007"

solver:
  trainer: "rbsolver_iter"
  log_interval: 100
  explore_iters: 5
  num_epochs: 1000
  max_lr: 0.003
  batch_size: 100
  save_freq: 20
  val_freq: 20
  scheduler: "ConstantScheduler"
  save_every: True
  save_mode: iteration
dataloader:
  pin_memory: True
input:
  shuffle: False
dataset:
  xarm_hec_sim:
    load_mask_pred: True
test:
  batch_size: 100
  do_evaluation: False
  evaluators: [ "" ]
  do_visualization: True
  visualizer: "rbsolver_hover_mask"

sim_hec:
  #  Tc_c2b: [ [ 9.738e-01,  2.276e-01,  0.000e+00,  2.704e-17 ],
  #            [ 7.784e-02, -3.330e-01, -9.397e-01,  3.372e-17 ],
  #            [ -2.139e-01,  9.150e-01, -3.420e-01,  8.000e-01 ],
  #            [ 0.000e+00,  0.000e+00,  0.000e+00,  1.000e+00 ] ]
  Tc_c2b_npy_path: "data/sim_for_hec/version2_se_cam10_qpos1000/poses.npy"
  Tc_c2b_index: 7
  step: False
  rt:
    enable: True
  add_desk_cube:
    enable: True
    half_size: [ 0.5, 0.5, 0.5 ]
    pose: [ -0.4, 0, -0.5 ]
