model:
  meta_architecture: "RBSolver"
  rbsolver_iter:
    data_dir: data/sim_for_hec/version2_no_marker_predinit_se_ncam80_nqpos2000/000018
  rbsolver:
    use_mask: pred
    init_Tc_c2b: [[ 0.8035, 0.5951, 0.0136, 0.0011],
 [ 0.3538,-0.4592,-0.8148, 0.0012],
 [-0.4787, 0.6595,-0.5795, 0.8213],
 [ 0.    , 0.    , 0.    , 1.    ]]

    #links: [ 0,1,2,3,4,5,6,7 ]
  space_explorer:
    sample: 80
    sample_limit: True
    n_sample_qposes: 2000
    urdf_path: "data/xarm7_with_gripper_reduced_dof.urdf"
    srdf_path: "data/xarm7_with_gripper_reduced_dof.srdf"
    move_group: "link_eef"
    max_dist_constraint:
      enable: True
      max_dist: 0.5
      max_dist_center_compute_n: 20000
    collision_check:
      enable: True
      use_pointcloud: False
      pc_sampled: 40000
      by_eef_pose: False
      ignore_posz_pts: True
      planning_time: 0.1
      dilate: 20
datasets:
  train: ("xarm_hec_sim_version2_no_marker_predinit_se_ncam80_nqpos2000/000018",)
  test: "xarm_hec_sim_version2_no_marker_predinit_se_ncam80_nqpos2000/000018"

solver:
  trainer: "rbsolver_iter"
  log_interval: 100
  explore_iters: 5
  num_epochs: 1000
  max_lr: 0.003
  batch_size: 100
  save_freq: 20
  val_freq: 20
  scheduler: "ConstantScheduler"
  save_every: True
  save_mode: iteration
dataloader:
  pin_memory: True
dataset:
  xarm_hec_sim:
    load_mask_pred: True
test:
  batch_size: 100
  do_evaluation: False
  evaluators: [ "" ]
  do_visualization: True
  visualizer: "rbsolver_hover_mask"

sim_hec:
  Tc_c2b: [[ 7.93893273e-01, 6.08057128e-01, 0.00000000e+00,-5.28022575e-19],
           [ 3.90851588e-01,-5.10304759e-01,-7.66044443e-01,-1.63300004e-16],
           [-4.65798784e-01, 6.08157530e-01,-6.42787610e-01, 8.00000000e-01],
           [ 0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 1.00000000e+00]]
  step: False
  rt:
    enable: True
  add_desk_cube:
    enable: True
    half_size: [ 0.5, 0.5, 0.5 ]
    pose: [ -0.4, 0, -0.5 ]
