model:
  meta_architecture: "RBSolver"
  rbsolver:
    use_mask: gt
    init_Tc_c2b: [ [ 0.00000000e+00,  1.00000000e+00,  0.00000000e+00,0.00000000e+00 ],
                   [ 1.73648178e-01,  0.00000000e+00, -9.84807753e-01,  2.32189595e-17 ],
                   [ -9.84807753e-01,  0.00000000e+00, -1.73648178e-01,7.00000000e-01 ],
                   [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,1.00000000e+00 ] ]

    #links: [ 0,1,2,3,4,5,6,7 ]
  space_explorer:
    variance_based_sampling: False
    sample_limit: True
    n_sample_qposes: 2000
    urdf_path: "data/xarm7_with_gripper_reduced_dof.urdf"
    srdf_path: "data/xarm7_with_gripper_reduced_dof.srdf"
    move_group: "link_eef"
    max_dist_constraint:
      enable: True
      max_dist: 0.5
      max_dist_center_compute_n: 20000
    collision_check:
      enable: True
      pc_sampled: 40000
datasets:
  train: ("xarm_hec_sim_version1_no_marker/000000",)
  test: "xarm_hec_sim_version1_no_marker/000000"

solver:
  num_epochs: 1000
  max_lr: 0.003
  batch_size: 100
  save_freq: 20
  val_freq: 20
  scheduler: "ConstantScheduler"
  save_every: True
  save_mode: iteration
dataloader:
  pin_memory: True
#dataset:
#  xarm_hec_sim:
#    load_mask_gt: True
test:
  batch_size: 100
  do_evaluation: False
  evaluators: [ "" ]
  do_visualization: True
  visualizer: "rbsolver_hover_mask"


#  space_explore:
#    start: 300
#    sample: 50 # camera poses sampled from start to end (steps[-1])
#    #    sample: 10 # camera poses sampled from start to end (steps[-1])
#    qpos_sample_method: random
#    n_sample_qposes: 1500
##    n_sample_qposes: 500
