data_dir: data/sim_hec_with_marker/version1/000000
use_gt_marker_pose: False
icp: False
cpa: False
#n: -1
subpixel: True
#fragments: [ [ 0,54 ] ]
#fragments: [ [ 0,10 ],[ 10,20 ],[ 20,30 ],[ 30,38 ],[ 38,46 ],[ 46,54 ] ]