model:
  meta_architecture: "RBSolver"
  rbsolver_iter:
    data_dir: data/sim_for_hec/version2_no_marker_predinit_se/000083
  rbsolver:
    use_mask: pred
    init_Tc_c2b: [[ 8.0110e-01, 5.9850e-01, 1.0000e-03,-5.0000e-04],
 [ 2.0600e-01,-2.7410e-01,-9.3940e-01,-1.5000e-03],
 [-5.6200e-01, 7.5280e-01,-3.4290e-01, 1.7955e+00],
 [ 0.0000e+00, 0.0000e+00, 0.0000e+00, 1.0000e+00]]

    #links: [ 0,1,2,3,4,5,6,7 ]
  space_explorer:
    sample: 50
    sample_limit: True
    n_sample_qposes: 2000
    urdf_path: "data/xarm7_with_gripper_reduced_dof.urdf"
    srdf_path: "data/xarm7_with_gripper_reduced_dof.srdf"
    move_group: "link_eef"
    max_dist_constraint:
      enable: True
      max_dist: 0.5
      max_dist_center_compute_n: 20000
    collision_check:
      enable: True
      pc_sampled: 40000
      ignore_posz_pts: True
      dilate: 20
datasets:
  train: ("xarm_hec_sim_version2_no_marker_predinit_se/000083",)
  test: "xarm_hec_sim_version2_no_marker_predinit_se/000083"

solver:
  trainer: "rbsolver_iter"
  log_interval: 100
  explore_iters: 5
  num_epochs: 1000
  max_lr: 0.003
  batch_size: 100
  save_freq: 20
  val_freq: 20
  scheduler: "ConstantScheduler"
  save_every: True
  save_mode: iteration
dataloader:
  pin_memory: True
dataset:
  xarm_hec_sim:
    load_mask_pred: True
test:
  batch_size: 100
  do_evaluation: False
  evaluators: [ "" ]
  do_visualization: True
  visualizer: "rbsolver_hover_mask"

sim_hec:
  Tc_c2b: [[ 7.93893273e-01, 6.08057128e-01, 0.00000000e+00, 8.63731167e-18],
           [ 2.07967786e-01,-2.71527491e-01,-9.39692621e-01, 1.74680348e-16],
           [-5.71386796e-01, 7.46015650e-01,-3.42020143e-01, 1.80000000e+00],
           [ 0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 1.00000000e+00]]
  step: False
  rt:
    enable: True
  add_desk_cube:
    enable: True
    half_size: [ 0.5, 0.5, 0.5 ]
    pose: [ -0.4, 0, -0.5 ]
